### ISSUE TITLE
is this available on a maven repository?

### ISSUE THREAD

**Issue by fommil** [mirkojahn/net.mjahn.hid.driver#1]
Because it would be great to be able to depend on this project via maven.

**Comment by mirkojahn** [comment]
Well, this version isn't, but a newer (binary) version is available here: https://github.com/cibuddy/cibuddy/tree/master/drivers/hid

The artifacts are currently exposed to the Sonar snapshopt repository (https://oss.sonatype.org/content/groups/public/com/cibuddy/drivers/), but as soon as the first final version is out (which should be rather soon), it will be available on maven central as well.

Does that help?

**Comment by fommil** [comment]
@mirkojahn that's cool – in the meantime I discovered that

```
            <groupId>com.codeminders</groupId>
            <artifactId>hidapi</artifactId>
            <version>1.1</version>
```

is already on maven central, so that solves my problem.

What does your library do that the codeminders one doesn't?

**Comment by mirkojahn** [comment]
API wise speaking - nothing. I just packaged the javahidapi native binaries (together with an arm6 binary I compiled) and the Java API in one jar that is OSGi compatible. So in one jar, you have everything you need to get started. In OSGi it is even simpler (no class path libary loading stuff), you just have to drop it into your container and it exposes an OSGi Service that allows you to interact with connected HID devices. I guess, as long as you're not considering OSGi as a deployment option, the "original" codeminders distribution should be sufficient.

**Comment by fommil** [comment]
@mirkojahn will your binary work on the Raspberry Pi? https://github.com/openyou/emokit/pull/55

**Comment by mirkojahn** [comment]
I have CIBuddy running on my Raspberry Pi for testing with multiple i-Buddies connected without any issues (CIBuddy is the actual project I am using the binaries in). However, this is not thoroughly tested and all I did was compiling the binaries on the Raspberry, so no magic there, though.

**Comment by fommil** [comment]
@mirkojahn oh that's hilarious – might actually convince me to get a jenkins nightly to pass! :-D

This is my project: https://github.com/fommil/emokit-java which uses `javahidapi` but I know some people are interested in the Raspberry Pi as a target platform. I don't want any users to have to build any binaries, so what would you recommend that I do? Ideally I'd like to simply swap out the maven `javahidapi` dependency for something that provides the same targets (OSX, Linux, Windows) plus Raspberry Pi (and anything else that would be sensible).
